import asyncio
import json
import re
from typing import Any

import httpx
from openai import (
    APIConnectionError,
    APIError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    RateLimitError,
    pydantic_function_tool,
)
from pydantic import ValidationError

from app.agent_runtime.contracts import (
    BaseAgentResult,
    ModelProvider,
    ModelRequest,
    ModelResponse,
    ModelToolCall,
    ModelUsage,
    ProviderCallError,
)
from app.agent_runtime.routing import ModelProfile
from app.core.config import Settings
from app.domain.exceptions import AgentRuntimeDomainError


class MockModelProvider:
    name = "mock"
    paid = False

    def __init__(
        self,
        *,
        response: Any | None = None,
        responses: list[Any] | None = None,
        usage: ModelUsage | None = None,
        error: ProviderCallError | None = None,
        delay_seconds: float = 0,
    ) -> None:
        self.response = response
        self.responses = responses
        self.call_count = 0
        self.requests: list[ModelRequest] = []
        self.usage = usage or ModelUsage(
            input_tokens=12,
            output_tokens=18,
            total_tokens=30,
            cached_input_tokens=2,
        )
        self.error = error
        self.delay_seconds = delay_seconds

    async def generate(self, request: ModelRequest) -> ModelResponse:
        self.call_count += 1
        self.requests.append(request)
        if self.delay_seconds:
            await asyncio.sleep(self.delay_seconds)
        if self.error is not None:
            raise self.error
        output = self.response
        if self.responses:
            output = self.responses[min(self.call_count - 1, len(self.responses) - 1)]
        if output is None and request.metadata.get("mock_scenario") == "filesystem_roundtrip":
            path = request.metadata.get("mock_path") or "forge-phase07.txt"
            content = request.metadata.get("mock_content") or "Forge autonomous execution"
            if self.call_count == 1:
                output = {
                    "type": "tool_call",
                    "tool_name": "filesystem.write",
                    "arguments": {"path": path, "content": content},
                }
            elif self.call_count == 2:
                output = {
                    "type": "tool_call",
                    "tool_name": "filesystem.read",
                    "arguments": {"path": path},
                }
            else:
                output = {
                    "type": "final",
                    "result": {
                        "status": "completed",
                        "summary": "Mock filesystem roundtrip completed.",
                        "output": {"path": path, "content": content},
                        "notes": ["Generated by the deterministic mock provider."],
                    },
                }
        if output is None and request.metadata.get("mock_scenario") == "filesystem_write":
            path = request.metadata.get("mock_path") or "brief.txt"
            content = request.metadata.get("mock_content") or "Forge project brief"
            output = (
                {
                    "type": "tool_call",
                    "tool_name": "filesystem.write",
                    "arguments": {"path": path, "content": content},
                }
                if self.call_count == 1
                else {
                    "type": "final",
                    "result": {
                        "status": "completed",
                        "summary": f"Wrote {path}.",
                        "output": {"path": path, "content": content},
                        "notes": ["Generated by the deterministic mock provider."],
                    },
                }
            )
        if output is None and request.metadata.get("mock_scenario") == "filesystem_read":
            path = request.metadata.get("mock_path") or "brief.txt"
            output = (
                {
                    "type": "tool_call",
                    "tool_name": "filesystem.read",
                    "arguments": {"path": path},
                }
                if self.call_count == 1
                else {
                    "type": "final",
                    "result": {
                        "status": "completed",
                        "summary": f"Verified {path}.",
                        "output": {"path": path, "verified": True},
                        "notes": ["Generated by the deterministic mock provider."],
                    },
                }
            )
        if output is None and request.response_model.__name__ == "PlanProposal":
            from app.planning.contracts import PlanProposal

            output = PlanProposal.model_validate(
                {
                    "project": {
                        "name": request.metadata.get("mission_title", "Forge Mission"),
                        "description": "A deterministic filesystem project generated by mock.",
                    },
                    "agents": [
                        {
                            "key": "generalist",
                            "name": "Mission Generalist",
                            "role": "GENERAL",
                            "description": "Creates and verifies the scoped project brief.",
                            "model_alias": "default",
                            "requested_permissions": {
                                "filesystem.read": True,
                                "filesystem.write": True,
                            },
                        }
                    ],
                    "tasks": [
                        {
                            "key": "write_brief",
                            "title": "Create project brief",
                            "description": "Write the Mission brief to brief.txt.",
                            "assigned_agent_key": "generalist",
                            "priority": "NORMAL",
                            "input": {
                                "mock_scenario": "filesystem_write",
                                "path": "brief.txt",
                                "content": "Forge Mission project brief",
                            },
                            "acceptance_criteria": ["brief.txt contains the project brief"],
                            "max_iterations": 2,
                        },
                        {
                            "key": "verify_brief",
                            "title": "Verify project brief",
                            "description": "Read brief.txt and verify its contents.",
                            "assigned_agent_key": "generalist",
                            "priority": "NORMAL",
                            "input": {"mock_scenario": "filesystem_read", "path": "brief.txt"},
                            "acceptance_criteria": ["brief.txt is readable and verified"],
                            "max_iterations": 2,
                        },
                    ],
                    "dependencies": [{"task": "verify_brief", "depends_on": "write_brief"}],
                }
            )
        if output is None:
            task_title = request.metadata.get("task_title", "task")
            result = BaseAgentResult(
                status="completed",
                summary=f"Mock execution completed for {task_title}.",
                output={"result": "deterministic-mock-output", "task": task_title},
                notes=["Generated by the local deterministic mock provider."],
            )
            output = (
                {"type": "final", "result": result.model_dump(mode="json")}
                if request.response_model.__name__ == "AgentTurnResponse"
                else result
            )
        return ModelResponse(
            output=output,
            usage=self.usage,
            provider=self.name,
            model=request.model,
            response_id=f"mock-response-{self.call_count}",
        )


class OpenAIModelProvider:
    def __init__(
        self,
        api_key: str,
        timeout_seconds: float,
        *,
        name: str = "openai",
        paid: bool = True,
        base_url: str | None = None,
    ) -> None:
        from openai import AsyncOpenAI

        self.name = name
        self.paid = paid
        self.client = AsyncOpenAI(
            api_key=api_key,
            timeout=timeout_seconds,
            max_retries=0,
            base_url=base_url,
        )

    @staticmethod
    def _native_tool_name(name: str) -> str:
        normalized = re.sub(r"[^a-zA-Z0-9_-]", "__", name)
        return f"forge__{normalized}"[:64]

    async def generate(self, request: ModelRequest) -> ModelResponse:
        native_name_to_forge: dict[str, str] = {}
        native_tools: list[dict[str, Any]] = []
        for tool in request.tools:
            native_name = self._native_tool_name(tool.name)
            if native_name in native_name_to_forge:
                raise ProviderCallError(
                    "MODEL_TOOL_SCHEMA_ERROR", "Model tool names are not uniquely representable"
                )
            native_name_to_forge[native_name] = tool.name
            native_tools.append(
                pydantic_function_tool(
                    tool.input_model,
                    name=native_name,
                    description=tool.description,
                )
            )

        parse_options: dict[str, Any] = {}
        if native_tools:
            parse_options.update(
                tools=native_tools,
                parallel_tool_calls=False,
                max_tool_calls=1,
            )
        try:
            response = await self.client.responses.parse(
                model=request.model,
                input=[
                    {"role": "system", "content": request.system_prompt},
                    {"role": "user", "content": request.user_prompt},
                ],
                text_format=BaseAgentResult if native_tools else request.response_model,
                **parse_options,
            )
        except APITimeoutError as exc:
            raise ProviderCallError(
                "MODEL_TIMEOUT",
                "The model request timed out",
                retryable=True,
                category="TIMEOUT",
                request_id=getattr(exc, "request_id", None),
                exception_type=type(exc).__name__,
            ) from exc
        except AuthenticationError as exc:
            raise ProviderCallError(
                "MODEL_AUTH_ERROR",
                "The model provider rejected authentication",
                category="AUTHENTICATION",
                http_status=getattr(exc, "status_code", None),
                request_id=getattr(exc, "request_id", None),
                exception_type=type(exc).__name__,
            ) from exc
        except RateLimitError as exc:
            details = self._provider_error_details(exc)
            quota_exhausted = details["provider_error_type"] == "insufficient_quota" or (
                details["provider_error_code"] in {"insufficient_quota", "credit_balance_exhausted"}
            )
            raise ProviderCallError(
                "MODEL_QUOTA_EXHAUSTED" if quota_exhausted else "MODEL_RATE_LIMIT",
                (
                    "The model provider API credit balance is exhausted"
                    if quota_exhausted
                    else "The model provider rate limit was reached"
                ),
                retryable=not quota_exhausted,
                category="QUOTA" if quota_exhausted else "RATE_LIMIT",
                **details,
            ) from exc
        except APIConnectionError as exc:
            raise ProviderCallError(
                "MODEL_PROVIDER_TEMPORARY",
                "The model provider is temporarily unreachable",
                retryable=True,
                category="NETWORK",
                request_id=getattr(exc, "request_id", None),
                exception_type=type(exc).__name__,
            ) from exc
        except APIStatusError as exc:
            details = self._provider_error_details(exc)
            status_code = details.get("http_status")
            temporary = isinstance(status_code, int) and (
                status_code in {408, 409, 425} or status_code >= 500
            )
            unavailable = status_code == 404
            raise ProviderCallError(
                (
                    "MODEL_PROVIDER_TEMPORARY"
                    if temporary
                    else "MODEL_UNAVAILABLE"
                    if unavailable
                    else "MODEL_CONFIGURATION_ERROR"
                ),
                (
                    "The model provider is temporarily unavailable"
                    if temporary
                    else "The configured model is unavailable"
                    if unavailable
                    else "The model provider rejected the configured request"
                ),
                retryable=temporary,
                category=(
                    "TEMPORARY_PROVIDER"
                    if temporary
                    else "MODEL_UNAVAILABLE"
                    if unavailable
                    else "CONFIGURATION"
                ),
                **details,
            ) from exc
        except ValidationError as exc:
            raise ProviderCallError(
                "INVALID_MODEL_OUTPUT",
                "The model returned a malformed structured result",
                category="RESPONSE_VALIDATION",
                exception_type=type(exc).__name__,
            ) from exc
        except APIError as exc:
            raise ProviderCallError(
                "MODEL_PROVIDER_ERROR",
                "The model provider request failed",
                category="PROVIDER",
                request_id=getattr(exc, "request_id", None),
                exception_type=type(exc).__name__,
            ) from exc

        usage_data = response.usage
        input_details = getattr(usage_data, "input_tokens_details", None)
        usage = ModelUsage(
            input_tokens=getattr(usage_data, "input_tokens", 0) or 0,
            output_tokens=getattr(usage_data, "output_tokens", 0) or 0,
            total_tokens=getattr(usage_data, "total_tokens", 0) or 0,
            cached_input_tokens=getattr(input_details, "cached_tokens", 0) or 0,
        )
        function_calls = [
            item for item in response.output if getattr(item, "type", None) == "function_call"
        ]
        if function_calls:
            if len(function_calls) != 1:
                raise ProviderCallError(
                    "INVALID_MODEL_OUTPUT", "The model returned more than one tool request"
                )
            function_call = function_calls[0]
            forge_name = native_name_to_forge.get(function_call.name)
            if forge_name is None:
                raise ProviderCallError(
                    "INVALID_MODEL_OUTPUT", "The model requested an unknown tool"
                )
            try:
                arguments = json.loads(function_call.arguments)
            except (TypeError, json.JSONDecodeError) as exc:
                raise ProviderCallError(
                    "INVALID_MODEL_OUTPUT", "The model returned invalid tool arguments"
                ) from exc
            if not isinstance(arguments, dict):
                raise ProviderCallError(
                    "INVALID_MODEL_OUTPUT", "The model tool arguments must be an object"
                )
            output: Any = {
                "type": "tool_call",
                "tool_name": forge_name,
                "arguments": arguments,
            }
        elif response.output_parsed is None:
            raise ProviderCallError(
                "INVALID_MODEL_OUTPUT", "The model did not return the required structured result"
            )
        else:
            output = response.output_parsed
        return ModelResponse(
            output=output,
            usage=usage,
            provider=self.name,
            model=request.model,
            response_id=response.id,
        )

    @staticmethod
    def _provider_error_details(error: APIStatusError) -> dict[str, Any]:
        body = getattr(error, "body", None)
        detail = body.get("error", body) if isinstance(body, dict) else {}
        if not isinstance(detail, dict):
            detail = {}
        return {
            "http_status": getattr(error, "status_code", None),
            "provider_error_code": detail.get("code"),
            "provider_error_type": detail.get("type"),
            "request_id": getattr(error, "request_id", None),
            "exception_type": type(error).__name__,
        }


class GeminiModelProvider:
    """Provider-neutral Gemini generateContent adapter with structured/tool output."""

    name = "gemini"

    def __init__(
        self,
        api_key: str,
        timeout_seconds: float,
        *,
        base_url: str,
        paid: bool,
    ) -> None:
        self.paid = paid
        self.client = httpx.AsyncClient(
            base_url=f"{base_url.rstrip('/')}/",
            timeout=timeout_seconds,
            headers={"x-goog-api-key": api_key, "content-type": "application/json"},
        )

    async def generate(self, request: ModelRequest) -> ModelResponse:
        generation: dict[str, Any] = {"responseMimeType": "application/json"}
        if not request.tools:
            generation["responseJsonSchema"] = self._gemini_schema(
                request.response_model.model_json_schema()
            )
        contents: list[dict[str, Any]] = [
            {
                "role": "user",
                "parts": [
                    {"text": request.conversation_start_prompt or request.user_prompt}
                ],
            }
        ]
        for exchange in request.tool_exchanges:
            model_content = exchange.call.provider_context.get("gemini_content")
            if not self._valid_model_tool_content(model_content):
                raise ProviderCallError(
                    "PROVIDER_TOOL_PROTOCOL_ERROR",
                    "Gemini tool continuation state is missing or invalid",
                    category="TOOL_PROTOCOL",
                )
            contents.append(model_content)
            native_name = OpenAIModelProvider._native_tool_name(exchange.call.name)
            function_response: dict[str, Any] = {
                "name": native_name,
                "response": exchange.response,
            }
            if exchange.call.call_id:
                function_response["id"] = exchange.call.call_id
            contents.append(
                {
                    "role": "user",
                    "parts": [{"functionResponse": function_response}],
                }
            )
        payload: dict[str, Any] = {
            "systemInstruction": {"parts": [{"text": request.system_prompt}]},
            "contents": contents,
            "generationConfig": generation,
        }
        native_to_forge: dict[str, str] = {}
        if request.tools:
            declarations = []
            for tool in request.tools:
                native = OpenAIModelProvider._native_tool_name(tool.name)
                native_to_forge[native] = tool.name
                declarations.append(
                    {
                        "name": native,
                        "description": tool.description,
                        "parametersJsonSchema": self._gemini_schema(
                            tool.input_model.model_json_schema()
                        ),
                    }
                )
            payload["tools"] = [{"functionDeclarations": declarations}]
            payload["toolConfig"] = {"functionCallingConfig": {"mode": "AUTO"}}
        try:
            response = await self.client.post(
                f"models/{request.model}:generateContent", json=payload
            )
        except httpx.TimeoutException as exc:
            raise ProviderCallError(
                "MODEL_TIMEOUT",
                "The model request timed out",
                retryable=True,
                category="TIMEOUT",
                exception_type=type(exc).__name__,
            ) from exc
        except httpx.NetworkError as exc:
            raise ProviderCallError(
                "MODEL_PROVIDER_TEMPORARY",
                "The model provider is temporarily unreachable",
                retryable=True,
                category="NETWORK",
                exception_type=type(exc).__name__,
            ) from exc
        if response.status_code >= 400:
            raise self._http_error(
                response,
                has_tools=bool(request.tools),
                is_tool_continuation=bool(request.tool_exchanges),
            )
        try:
            body = response.json()
            candidate = body["candidates"][0]
            content = candidate["content"]
            parts = content["parts"]
        except (ValueError, KeyError, IndexError, TypeError) as exc:
            raise ProviderCallError(
                "PROVIDER_RESPONSE_INVALID",
                "The model provider returned a malformed response",
                category="RESPONSE_VALIDATION",
                http_status=response.status_code,
                exception_type=type(exc).__name__,
            ) from exc
        function_parts = [part["functionCall"] for part in parts if "functionCall" in part]
        if function_parts:
            if len(function_parts) != 1:
                raise ProviderCallError(
                    "PROVIDER_TOOL_PROTOCOL_ERROR",
                    "The model returned an unsupported number of tool requests",
                    category="TOOL_PROTOCOL",
                )
            call = function_parts[0]
            forge_name = native_to_forge.get(str(call.get("name", "")))
            if forge_name is None or not isinstance(call.get("args"), dict):
                raise ProviderCallError(
                    "PROVIDER_TOOL_PROTOCOL_ERROR",
                    "The model returned an invalid tool request",
                    category="TOOL_PROTOCOL",
                )
            output: Any = {
                "type": "tool_call",
                "tool_name": forge_name,
                "arguments": call["args"],
            }
            tool_call = ModelToolCall(
                name=forge_name,
                arguments=call["args"],
                call_id=str(call["id"]) if call.get("id") else None,
                provider_context={"gemini_content": content},
            )
        else:
            text = "".join(str(part.get("text", "")) for part in parts)
            finish_reason = str(candidate.get("finishReason", "UNKNOWN"))
            if not text.strip():
                raise ProviderCallError(
                    "PROVIDER_RESPONSE_INVALID",
                    "The model provider returned no usable content "
                    f"(finish reason: {finish_reason})",
                    category="RESPONSE_VALIDATION",
                    http_status=response.status_code,
                    details=self._response_evidence(
                        candidate=candidate,
                        body=body,
                        parsed=None,
                        text=text,
                    ),
                )
            try:
                parsed = json.loads(text)
            except json.JSONDecodeError as exc:
                raise ProviderCallError(
                    "INVALID_MODEL_OUTPUT",
                    "The model returned malformed JSON",
                    category="RESPONSE_VALIDATION",
                    http_status=response.status_code,
                    exception_type=type(exc).__name__,
                    details={
                        **self._response_evidence(
                            candidate=candidate,
                            body=body,
                            parsed=None,
                            text=text,
                        ),
                        "validation_errors": [
                            {
                                "field": "$",
                                "expected": "valid JSON",
                                "received": {"type": "string", "length": len(text)},
                                "error_type": "json_invalid",
                            }
                        ],
                    },
                ) from exc
            try:
                output = request.response_model.model_validate(parsed)
            except ValidationError as exc:
                raise ProviderCallError(
                    "INVALID_MODEL_OUTPUT",
                    "The model returned a malformed structured result",
                    category="RESPONSE_VALIDATION",
                    http_status=response.status_code,
                    exception_type=type(exc).__name__,
                    details={
                        **self._response_evidence(
                            candidate=candidate,
                            body=body,
                            parsed=parsed,
                            text=text,
                        ),
                        "validation_errors": self._validation_errors(exc),
                    },
                ) from exc
            tool_call = None
        raw_usage = body.get("usageMetadata", {})
        usage = ModelUsage(
            input_tokens=int(raw_usage.get("promptTokenCount", 0) or 0),
            output_tokens=int(raw_usage.get("candidatesTokenCount", 0) or 0),
            total_tokens=int(raw_usage.get("totalTokenCount", 0) or 0),
            cached_input_tokens=int(raw_usage.get("cachedContentTokenCount", 0) or 0),
        )
        return ModelResponse(
            output=output,
            usage=usage,
            provider=self.name,
            model=request.model,
            response_id=response.headers.get("x-request-id"),
            tool_call=tool_call,
        )

    @staticmethod
    def _http_error(
        response: httpx.Response,
        *,
        has_tools: bool = False,
        is_tool_continuation: bool = False,
    ) -> ProviderCallError:
        try:
            detail = response.json().get("error", {})
        except ValueError:
            detail = {}
        status = response.status_code
        provider_status = str(detail.get("status", ""))
        message = str(detail.get("message", "")).lower()
        quota = status == 429 and ("quota" in message or provider_status == "RESOURCE_EXHAUSTED")
        auth = status in {401, 403}
        unavailable = status == 404
        temporary = status in {408, 409, 425, 429} or status >= 500
        if quota:
            code, category, retryable = "MODEL_QUOTA_EXHAUSTED", "QUOTA", False
        elif auth:
            code, category, retryable = "MODEL_AUTH_ERROR", "AUTHENTICATION", False
        elif unavailable:
            code, category, retryable = "MODEL_UNAVAILABLE", "MODEL_UNAVAILABLE", False
        elif temporary:
            code, category, retryable = (
                "MODEL_RATE_LIMIT" if status == 429 else "MODEL_PROVIDER_TEMPORARY",
                "RATE_LIMIT" if status == 429 else "TEMPORARY_PROVIDER",
                True,
            )
        elif status == 400 and is_tool_continuation and (
            "signature" in message or "function" in message
        ):
            code, category, retryable = (
                "PROVIDER_TOOL_PROTOCOL_ERROR",
                "TOOL_PROTOCOL",
                False,
            )
        elif status == 400 and has_tools and (
            "schema" in message or "function declaration" in message
        ):
            code, category, retryable = (
                "PROVIDER_TOOL_SCHEMA_INVALID",
                "TOOL_SCHEMA",
                False,
            )
        elif status == 400:
            code, category, retryable = "PROVIDER_REQUEST_INVALID", "REQUEST", False
        else:
            code, category, retryable = "MODEL_CONFIGURATION_ERROR", "CONFIGURATION", False
        return ProviderCallError(
            code,
            "The model provider request failed",
            retryable=retryable,
            category=category,
            http_status=status,
            provider_error_code=provider_status or None,
            request_id=response.headers.get("x-request-id"),
        )

    @staticmethod
    def _valid_model_tool_content(value: Any) -> bool:
        if not isinstance(value, dict) or value.get("role") != "model":
            return False
        parts = value.get("parts")
        return isinstance(parts, list) and any(
            isinstance(part, dict) and isinstance(part.get("functionCall"), dict)
            for part in parts
        )

    @classmethod
    def _validation_errors(cls, error: ValidationError) -> list[dict[str, Any]]:
        evidence: list[dict[str, Any]] = []
        expected_types = {
            "list_type": "array",
            "dict_type": "object",
            "string_type": "string",
            "bool_type": "boolean",
            "int_type": "integer",
            "enum": "one of the configured enum values",
            "literal_error": "the required literal value",
            "missing": "required field",
            "extra_forbidden": "no additional property",
            "string_pattern_mismatch": "string matching the required pattern",
            "string_too_long": "string within the maximum length",
            "string_too_short": "non-empty string within the minimum length",
            "too_long": "collection within the maximum size",
            "too_short": "non-empty collection within the minimum size",
        }
        for item in error.errors()[:20]:
            received = item.get("input")
            received_shape: dict[str, Any] = {"type": cls._json_type(received)}
            if isinstance(received, str | list | dict):
                received_shape["length"] = len(received)
            error_type = str(item.get("type", "validation_error"))
            evidence.append(
                {
                    "field": cls._field_path(item.get("loc", ())),
                    "expected": expected_types.get(error_type, str(item.get("msg", "valid value"))),
                    "received": received_shape,
                    "error_type": error_type,
                }
            )
        return evidence

    @staticmethod
    def _field_path(location: Any) -> str:
        path = "$"
        for item in location:
            if isinstance(item, int):
                path += f"[{item}]"
            else:
                path += f".{item}"
        return path

    @staticmethod
    def _json_type(value: Any) -> str:
        if value is None:
            return "null"
        if isinstance(value, bool):
            return "boolean"
        if isinstance(value, str):
            return "string"
        if isinstance(value, list):
            return "array"
        if isinstance(value, dict):
            return "object"
        if isinstance(value, int):
            return "integer"
        if isinstance(value, float):
            return "number"
        return type(value).__name__

    @classmethod
    def _response_evidence(
        cls,
        *,
        candidate: dict[str, Any],
        body: dict[str, Any],
        parsed: Any,
        text: str,
    ) -> dict[str, Any]:
        content = candidate.get("content")
        parts = content.get("parts") if isinstance(content, dict) else []
        return {
            "http_status": 200,
            "finish_reason": str(candidate.get("finishReason", "UNKNOWN")),
            "candidate_count": len(body.get("candidates") or []),
            "content_exists": isinstance(content, dict),
            "part_types": [
                sorted(str(key) for key in part if key != "thoughtSignature")
                for part in parts
                if isinstance(part, dict)
            ][:10],
            "response_shape": {
                "type": cls._json_type(parsed),
                "top_level_fields": sorted(parsed)[:50] if isinstance(parsed, dict) else [],
                "text_length": len(text),
            },
        }

    @classmethod
    def _gemini_schema(cls, schema: dict[str, Any]) -> dict[str, Any]:
        """Reduce Pydantic JSON Schema to Gemini's supported wire subset.

        Forge's Pydantic input model remains authoritative at tool execution.
        """

        supported = {
            "$id",
            "$defs",
            "$ref",
            "$anchor",
            "type",
            "format",
            "description",
            "enum",
            "items",
            "prefixItems",
            "minItems",
            "maxItems",
            "minimum",
            "maximum",
            "anyOf",
            "oneOf",
            "properties",
            "additionalProperties",
            "required",
        }

        def normalize(value: Any, *, property_map: bool = False) -> Any:
            if isinstance(value, list):
                return [normalize(item) for item in value]
            if not isinstance(value, dict):
                return value
            if property_map:
                return {key: normalize(item) for key, item in value.items()}
            normalized: dict[str, Any] = {}
            constraints: list[str] = []
            if isinstance(value.get("minLength"), int):
                constraints.append(f"minimum length {value['minLength']}")
            if isinstance(value.get("maxLength"), int):
                constraints.append(f"maximum length {value['maxLength']}")
            if isinstance(value.get("pattern"), str):
                constraints.append(f"must match pattern {value['pattern']}")
            for key, item in value.items():
                if key == "const":
                    normalized["enum"] = [normalize(item)]
                    continue
                if key not in supported:
                    continue
                normalized[key] = normalize(item, property_map=key in {"properties", "$defs"})
            if constraints:
                existing = str(normalized.get("description", "")).strip()
                constraint_text = "Constraints: " + "; ".join(constraints) + "."
                normalized["description"] = (
                    f"{existing} {constraint_text}".strip() if existing else constraint_text
                )
            return normalized

        result = normalize(schema)
        if not isinstance(result, dict) or result.get("type") != "object":
            raise ProviderCallError(
                "PROVIDER_TOOL_SCHEMA_INVALID",
                "Forge produced a tool schema that Gemini cannot accept",
                category="TOOL_SCHEMA",
            )
        return result


def provider_from_settings(
    settings: Settings,
    provider_name: str | None = None,
    *,
    paid: bool | None = None,
) -> ModelProvider:
    provider_name = (provider_name or settings.model_provider).strip().lower()
    if provider_name == "mock":
        return MockModelProvider()
    if provider_name == "openai":
        key = settings.openai_api_key
        api_key = key.get_secret_value() if key is not None else ""
        return OpenAIModelProvider(
            api_key,
            settings.model_request_timeout_seconds,
            name="openai",
            paid=True if paid is None else paid,
            base_url=settings.openai_base_url,
        )
    if provider_name == "openrouter":
        key = settings.openrouter_api_key
        api_key = key.get_secret_value() if key is not None else ""
        return OpenAIModelProvider(
            api_key,
            settings.model_request_timeout_seconds,
            name="openrouter",
            paid=True if paid is None else paid,
            base_url=settings.openrouter_base_url,
        )
    if provider_name == "gemini":
        key = settings.gemini_api_key
        api_key = key.get_secret_value() if key is not None else ""
        return GeminiModelProvider(
            api_key,
            settings.model_request_timeout_seconds,
            base_url=settings.gemini_base_url,
            paid=False if paid is None else paid,
        )
    raise AgentRuntimeDomainError(
        "MODEL_PROVIDER_ERROR", f"Unsupported model provider '{provider_name}'", 500
    )


def provider_for_profile(settings: Settings, profile: ModelProfile) -> ModelProvider:
    return provider_from_settings(settings, profile.provider, paid=profile.paid)
